export const ASSET_URLS = Object.freeze({
  warehouse: Object.freeze({
    wall: '/models-v3/warehouse/concrete-wall.glb',
    exterior: '/models-v19/warehouse/warehouse.glb',
    loadingDoorFrame: '/models-v8/warehouse/automatic-loading-door-frame.glb',
    loadingDoorLeaf: '/models-v8/warehouse/automatic-loading-door-leaf.glb',
    growBench: '/models-v3/warehouse/grow-bench.glb',
    shelf: '/models-v3/warehouse/shelf.glb',
    growLight: '/models-v3/warehouse/grow-light.glb',
    vendorCounter: '/models-v3/warehouse/vendor-counter.glb',
    soilPallet: '/models-v33/warehouse/soil-pallet.glb?v=1',
    airConditioner: '/models-v34/warehouse/wall-air-conditioner.glb?v=1',
    exhaustFan: '/models-v33/warehouse/exhaust-fan.glb?v=1',
    recyclingBin: '/models-v33/warehouse/recycling-bin.glb?v=1',
  }),
  city: Object.freeze({
    shop: '/models-v23/city-pack/residential-9004-house.glb?v=1',
    house: '/models-v5/city/house.glb',
  }),
  street: Object.freeze({
    lamp: '/models-v9/street/streetlamp.glb',
    tree: '/models-v9/street/tree.glb',
    shrub: '/models-v9/street/shrub-planter.glb',
    van: '/models-v9/street/delivery-van.glb',
    loadingZone: '/models-v9/street/loading-zone-cluster.glb',
    furniture: '/models-v9/street/street-furniture-cluster.glb',
    neighborOlder: '/models-v9/street/neighbor-older-idle.glb',
    househeadIdle: '/models-v24/characters/househead-idle.glb?v=1',
    foxWalker: '/models-v30/characters/fox-walk.glb?v=1',
    neonCatWalker: '/models-v31/characters/neon-cat-walk.glb?v=1',
    cat: '/models-v9/street/street-cat.glb',
    simpleHouseA: '/models-v10/city/simple-house-a.glb',
    simpleHouseB: '/models-v10/city/simple-house-b.glb',
    simpleHouseC: '/models-v13/city/detailed-house-c.glb',
    simpleHouseD: '/models-v13/city/detailed-house-d.glb',
    simpleHouseE: '/models-v18/city/low-poly-house.glb',
    simpleHouseF: '/models-v14/city/simple-house-f.glb',
    simpleHouseG: '/models-v14/city/simple-house-g.glb',
    simpleHouseH: '/models-v14/city/simple-house-h.glb',
    infillHouse1: '/models-v19/city/low-poly-house-neww.glb',
    infillHouse2: '/models-v19/city/low-poly-house-new2.glb',
    infillHouse3: '/models-v19/city/low-poly-house-new3.glb',
    infillHouse4: '/models-v19/city/low-poly-house-new4.glb',
    infillHouse5: '/models-v20/city/low-poly-house-67-ground-clean.glb',
    cityPackHighrise: '/models-v21/city-pack/highrise.glb?v=1',
    cityPackMotel: '/models-v21/city-pack/motel.glb?v=1',
    cityPackKfc: '/models-v21/city-pack/kfc.glb?v=1',
    cityPackResidential: '/models-v21/city-pack/residential-block.glb?v=1',
    cityPackCommercialTower: '/models-v21/city-pack/commercial-tower.glb?v=1',
    cityPackCommercialPurple: '/models-v21/city-pack/commercial-purple.glb?v=1',
    cityPackDiner: '/models-v21/city-pack/diner.glb?v=1',
    restaurant: '/models-v17/city/restaurant.glb',
    restaurantInterior: '/models-v17/interiors/restaurant-in-the-evening.glb',
  }),
  items: Object.freeze({
    seedPack: '/models-v7/items/robinhood-seed-pack-clean.glb',
    stockSeedPacks: Object.freeze({
      MSFT: '/models-v26/items/stock-seed-packs/msft-seed-pack.glb?v=2',
      TSLA: '/models-v26/items/stock-seed-packs/tsla-seed-pack.glb?v=2',
      NVDA: '/models-v26/items/stock-seed-packs/nvda-seed-pack.glb?v=2',
      MSTR: '/models-v26/items/stock-seed-packs/mstr-seed-pack.glb?v=2',
      AAPL: '/models-v26/items/stock-seed-packs/aapl-seed-pack.glb?v=2',
      QQQ: '/models-v29/items/stock-seed-packs/qqq-seed-pack.glb?v=5',
      GOOGL: '/models-v26/items/stock-seed-packs/googl-seed-pack.glb?v=2',
    }),
  }),
  plants: Object.freeze({
    matureBudCluster: '/models-v32/plants/meshy-cannabis-bud.glb?v=1',
  }),
  textures: Object.freeze({
    growthDiagram: '/textures/warehouse/pizarra.png?v=1',
  }),
  branding: Object.freeze({
    mark: '/brands/robinhood-chain-mark.svg',
  }),
  vendor: Object.freeze({
    idle: '/models-v37/characters/vlad-tenev-idle.glb?v=2',
    talk: '/models-v37/characters/vlad-tenev-talk.glb?v=2',
  }),
});

export function vendorClipForPanel(isOpen) {
  return isOpen ? 'talk' : 'idle';
}
